sudo: required

language: php

php:
  - 5.5
  - 5.4

env:
  - DB=mysql
  - DB=mariadb
  - DB=postgres

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.5
      env: DB=postgres

before_install: echo "before install"

install:
  - echo "install begin"
  - sudo apt-get install python
  - curl https://bootstrap.pypa.io/get-pip.py | sudo bash
  - sudo pip install json2yaml
  - echo "install end"

before_script: echo "before script"

script:
  - echo "script begin ($TRAVIS_PHP_VERSION $DB)"
  - phpunit Test.php
  - yaml2json .travis.yml
  - echo "script end"

after_success:
  - echo "after success begin"
  - false
  - echo "after success end"

after_failure: echo "after failure"

after_script: echo "after script"
